name: Publish NuGet Package

on:
  push:
    tags:
      - '*.*.**'
    
jobs:
  oublish_nuget_package:

    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        run: |
          sed -i -e "s/<!-- Version -->/$(echo '${{ github.ref_name }}' | sed 's/^v//')/" ./QuickLink/QuickLink.csproj
      - name: Pack
        run: dotnet pack ./QuickLink/QuickLink.csproj -c Release -o ./artifacts
      - name: Publish
        run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s https://api.nuget.org/v3/index.json